model:
  name: "ssd-10"
  version: "1.0"
  architecture: "single_stage"
  
input:
  tensor_name: "image"
  shape: [1, 3, 1200, 1200]
  data_type: "float32"
  preprocessing:
    resize: 
      strategy: "direct"      # SSD uses direct resize (may distort aspect ratio)
      target: [1200, 1200]
      padding_value: 0.0      # No padding used in SSD
    normalize:
      type: "custom"          # SSD uses ImageNet mean subtraction
      mean: [123.68, 116.78, 103.94]  # ImageNet means (RGB order)
      std: [1.0, 1.0, 1.0]    # No standard deviation normalization
    layout:
      format: "NCHW"          # Batch, Channels, Height, Width
      channel_order: "RGB"    # RGB color order

output:
  format: "ssd"
  architecture_type: "single_stage"
  unified_head: false         # SSD has separate classification and localization heads
  anchor_based: true          # SSD uses default boxes (anchors)
  multi_scale: true           # Six feature map scales
  coordinate_format: "corner" # SSD outputs corner coordinates (x1, y1, x2, y2)
  
  # Multi-scale feature map configuration
  scales:
    - name: "scale_1"
      feature_map_size: [150, 150]  # 1200/8 = 150
      stride: 8
      num_default_boxes: 4
      classification_tensor: "classification_1"
      localization_tensor: "localization_1"
      classification_shape: [1, 16, 150, 150]  # 4 boxes × 4 classes
      localization_shape: [1, 16, 150, 150]    # 4 boxes × 4 coordinates
      
    - name: "scale_2"
      feature_map_size: [75, 75]    # 1200/16 = 75
      stride: 16
      num_default_boxes: 6
      classification_tensor: "classification_2"
      localization_tensor: "localization_2"
      classification_shape: [1, 24, 75, 75]    # 6 boxes × 4 classes
      localization_shape: [1, 24, 75, 75]      # 6 boxes × 4 coordinates
      
    - name: "scale_3"
      feature_map_size: [38, 38]    # 1200/32 ≈ 38
      stride: 32
      num_default_boxes: 6
      classification_tensor: "classification_3"
      localization_tensor: "localization_3"
      classification_shape: [1, 24, 38, 38]    # 6 boxes × 4 classes
      localization_shape: [1, 24, 38, 38]      # 6 boxes × 4 coordinates
      
    - name: "scale_4"
      feature_map_size: [19, 19]    # 1200/64 ≈ 19
      stride: 64
      num_default_boxes: 6
      classification_tensor: "classification_4"
      localization_tensor: "localization_4"
      classification_shape: [1, 24, 19, 19]    # 6 boxes × 4 classes
      localization_shape: [1, 24, 19, 19]      # 6 boxes × 4 coordinates
      
    - name: "scale_5"
      feature_map_size: [10, 10]    # 1200/120 = 10
      stride: 120
      num_default_boxes: 4
      classification_tensor: "classification_5"
      localization_tensor: "localization_5"
      classification_shape: [1, 16, 10, 10]    # 4 boxes × 4 classes
      localization_shape: [1, 16, 10, 10]      # 4 boxes × 4 coordinates
      
    - name: "scale_6"
      feature_map_size: [5, 5]      # 1200/240 = 5
      stride: 240
      num_default_boxes: 4
      classification_tensor: "classification_6"
      localization_tensor: "localization_6"
      classification_shape: [1, 16, 5, 5]      # 4 boxes × 4 classes
      localization_shape: [1, 16, 5, 5]        # 4 boxes × 4 coordinates

  # Default box (anchor) configuration
  default_boxes:
    # Default box sizes (min_size, max_size) for each scale
    sizes: [30, 60, 111, 162, 213, 264, 315]
    
    # Aspect ratios for each scale
    aspect_ratios:
      scale_1: [2]           # 4 boxes: [1, 1_extra, 2, 1/2]
      scale_2: [2, 3]        # 6 boxes: [1, 1_extra, 2, 1/2, 3, 1/3]
      scale_3: [2, 3]        # 6 boxes: [1, 1_extra, 2, 1/2, 3, 1/3]
      scale_4: [2, 3]        # 6 boxes: [1, 1_extra, 2, 1/2, 3, 1/3]
      scale_5: [2]           # 4 boxes: [1, 1_extra, 2, 1/2]
      scale_6: [2]           # 4 boxes: [1, 1_extra, 2, 1/2]

  # Class information
  classes:
    num_classes: 4           # Including background class
    background_class: true   # SSD includes background class
    class_names:
      - "background"         # Class 0
      - "person"            # Class 1
      - "bicycle"           # Class 2
      - "car"               # Class 3

  # Postprocessing configuration
  postprocessing:
    confidence_threshold: 0.5      # Minimum confidence for detections
    nms_threshold: 0.45            # NMS IoU threshold
    max_detections: 200            # Maximum detections per image
    class_agnostic_nms: false      # Apply NMS per class (SSD standard)
    background_threshold: 0.01     # Background class threshold
    coordinate_decoding: "ssd"     # SSD-specific coordinate decoding
    variance: [0.1, 0.2]          # Variance values for coordinate decoding
    
    # Multi-class specific settings
    keep_top_k: 100               # Keep top K detections after NMS
    per_class_max: 50             # Maximum detections per class