# YOLOv2-COCO-9 Configuration File with compatible format
# This configuration file specifies the parameters for YOLOv2 object detection model

input:
  tensor_name: "input.1"
  shape: [1, 3, 416, 416]  # YOLOv2 expects [batch, channels, height, width]

output:
  postprocessing:
    confidence_threshold: 0.25
    nms_threshold: 0.45
    nms_enabled: true
    max_detections: 300
    objectness_threshold: 0.5
    class_agnostic_nms: false
    coordinate_decoding: "yolov2"