# YOLOv2-COCO-9 Configuration File
# This configuration file specifies the parameters for YOLOv2 object detection model

model:
  name: "yolov2-coco-9"
  version: "2.0"
  type: "object_detection"
  architecture: "yolov2"

input:
  image_size: [416, 416]  # YOLOv2 standard input size
  channels: 3
  color_space: "RGB"
  data_format: "NCHW"
  normalization:
    type: "zero_to_one"  # pixel values normalized to [0, 1]
    mean: [0.0, 0.0, 0.0]
    std: [1.0, 1.0, 1.0]

preprocessing:
  resize_strategy: "letterbox"  # maintain aspect ratio with padding
  maintain_aspect_ratio: true
  pad_color: [114, 114, 114]  # gray padding

output:
  format: "yolov2"
  architecture_type: "single_stage"
  unified_head: true
  anchor_based: true
  grid_size: [13, 13]  # 416/32 = 13x13 grid
  num_anchors: 5
  num_classes: 80
  confidence_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 300
  
  # Anchor boxes (width, height) for YOLOv2
  anchors:
    - [0.57273, 0.677385]    # anchor 1
    - [1.87446, 2.06253]     # anchor 2  
    - [3.33843, 5.47434]     # anchor 3
    - [7.88282, 3.52778]     # anchor 4
    - [9.77052, 9.16828]     # anchor 5

  tensor_structure:
    - name: "output"
      shape: [1, 425, 13, 13]  # 5 anchors × 85 predictions per anchor = 425 channels
      content:
        bbox_coords: 4      # tx, ty, tw, th per anchor
        objectness: 1       # confidence score per anchor
        class_logits: 80    # COCO class probabilities per anchor

postprocessing:
  nms_enabled: true
  score_threshold: 0.25
  iou_threshold: 0.45
  top_k: 300
  coordinate_decoding: "yolov2_style"  # tx, ty offsets + tw, th log-space

execution:
  provider: "CPU"
  intra_op_num_threads: 4
  inter_op_num_threads: 1
  execution_mode: "sequential"
  graph_optimization_level: "all"

classes:
  # COCO dataset class names (80 classes) - same as YOLOv8
  names:
    0: "person"
    1: "bicycle"
    2: "car"
    3: "motorcycle"
    4: "airplane"
    5: "bus"
    6: "train"
    7: "truck"
    8: "boat"
    9: "traffic light"
    10: "fire hydrant"
    11: "stop sign"
    12: "parking meter"
    13: "bench"
    14: "bird"
    15: "cat"
    16: "dog"
    17: "horse"
    18: "sheep"
    19: "cow"
    20: "elephant"
    21: "bear"
    22: "zebra"
    23: "giraffe"
    24: "backpack"
    25: "umbrella"
    26: "handbag"
    27: "tie"
    28: "suitcase"
    29: "frisbee"
    30: "skis"
    31: "snowboard"
    32: "sports ball"
    33: "kite"
    34: "baseball bat"
    35: "baseball glove"
    36: "skateboard"
    37: "surfboard"
    38: "tennis racket"
    39: "bottle"
    40: "wine glass"
    41: "cup"
    42: "fork"
    43: "knife"
    44: "spoon"
    45: "bowl"
    46: "banana"
    47: "apple"
    48: "sandwich"
    49: "orange"
    50: "broccoli"
    51: "carrot"
    52: "hot dog"
    53: "pizza"
    54: "donut"
    55: "cake"
    56: "chair"
    57: "couch"
    58: "potted plant"
    59: "bed"
    60: "dining table"
    61: "toilet"
    62: "tv"
    63: "laptop"
    64: "mouse"
    65: "remote"
    66: "keyboard"
    67: "cell phone"
    68: "microwave"
    69: "oven"
    70: "toaster"
    71: "sink"
    72: "refrigerator"
    73: "book"
    74: "clock"
    75: "vase"
    76: "scissors"
    77: "teddy bear"
    78: "hair drier"
    79: "toothbrush"