model:
  name: "yolov3-10"
  version: "3.0"
  architecture: "single_stage"
  
input:
  tensor_name: "input"
  shape: [1, 3, 416, 416]
  data_type: "float32"
  preprocessing:
    resize: 
      strategy: "letterbox"  # YOLOv3 uses letterbox to maintain aspect ratio
      target: [416, 416]
      padding_value: 0.5     # Gray padding (128/255 = 0.5)
    normalize:
      type: "zero_to_one"    # Divide by 255.0
    layout:
      format: "NCHW"         # Batch, Channels, Height, Width
      channel_order: "RGB"   # RGB color order

output:
  format: "yolov3"
  architecture_type: "single_stage"
  unified_head: false        # YOLOv3 has multiple detection heads
  anchor_based: true         # YOLOv3 uses anchor boxes
  multi_scale: true          # Three detection scales
  
  # Multi-scale detection configuration
  scales:
    - name: "large_objects"
      grid_size: [13, 13]    # 416/32 = 13
      tensor_name: "output0"
      tensor_shape: [1, 255, 13, 13]
      anchor_indices: [6, 7, 8]  # Large anchors
      
    - name: "medium_objects" 
      grid_size: [26, 26]    # 416/16 = 26
      tensor_name: "output1"
      tensor_shape: [1, 255, 26, 26]
      anchor_indices: [3, 4, 5]  # Medium anchors
      
    - name: "small_objects"
      grid_size: [52, 52]    # 416/8 = 52
      tensor_name: "output2"
      tensor_shape: [1, 255, 52, 52]
      anchor_indices: [0, 1, 2]  # Small anchors

  # Anchor box definitions (width, height) for 416x416 input
  anchors:
    - [10, 13]    # 0: Small anchor 1
    - [16, 30]    # 1: Small anchor 2
    - [33, 23]    # 2: Small anchor 3
    - [30, 61]    # 3: Medium anchor 1
    - [62, 45]    # 4: Medium anchor 2
    - [59, 119]   # 5: Medium anchor 3
    - [116, 90]   # 6: Large anchor 1
    - [156, 198]  # 7: Large anchor 2
    - [373, 326]  # 8: Large anchor 3

  tensor_structure:
    anchors_per_scale: 3
    predictions_per_anchor: 85  # 4 (bbox) + 1 (objectness) + 80 (classes)
    total_channels: 255         # 3 × 85 = 255
    content:
      bbox_coords: 4            # tx, ty, tw, th per anchor
      objectness: 1             # confidence score per anchor
      class_logits: 80          # COCO class probabilities per anchor

  coordinate_format: "center_width_height"
  coordinate_system: "grid_relative"  # Coordinates relative to grid cells
  
postprocessing:
  nms_enabled: true
  confidence_threshold: 0.7     # Higher threshold for YOLOv3
  objectness_threshold: 0.7     # Objectness confidence threshold
  nms_threshold: 0.45           # IoU threshold for NMS
  max_detections: 300
  class_agnostic_nms: false     # Apply NMS per class
  coordinate_decoding: "yolov3_style"  # YOLOv3 coordinate transformations

# Multi-scale processing configuration  
processing:
  scale_fusion: "combine"       # Combine all scales before NMS
  scale_weights: [1.0, 1.0, 1.0]  # Equal weight for all scales
  small_object_boost: 1.1       # Slight boost for small object detections

execution:
  provider: "CPU"
  intra_op_num_threads: 4
  inter_op_num_threads: 1
  execution_mode: "sequential"
  graph_optimization_level: "all"

classes:
  # COCO dataset class names (80 classes) - same as other YOLO versions
  names:
    0: "person"
    1: "bicycle"
    2: "car"
    3: "motorcycle"
    4: "airplane"
    5: "bus"
    6: "train"
    7: "truck"
    8: "boat"
    9: "traffic light"
    10: "fire hydrant"
    11: "stop sign"
    12: "parking meter"
    13: "bench"
    14: "bird"
    15: "cat"
    16: "dog"
    17: "horse"
    18: "sheep"
    19: "cow"
    20: "elephant"
    21: "bear"
    22: "zebra"
    23: "giraffe"
    24: "backpack"
    25: "umbrella"
    26: "handbag"
    27: "tie"
    28: "suitcase"
    29: "frisbee"
    30: "skis"
    31: "snowboard"
    32: "sports ball"
    33: "kite"
    34: "baseball bat"
    35: "baseball glove"
    36: "skateboard"
    37: "surfboard"
    38: "tennis racket"
    39: "bottle"
    40: "wine glass"
    41: "cup"
    42: "fork"
    43: "knife"
    44: "spoon"
    45: "bowl"
    46: "banana"
    47: "apple"
    48: "sandwich"
    49: "orange"
    50: "broccoli"
    51: "carrot"
    52: "hot dog"
    53: "pizza"
    54: "donut"
    55: "cake"
    56: "chair"
    57: "couch"
    58: "potted plant"
    59: "bed"
    60: "dining table"
    61: "toilet"
    62: "tv"
    63: "laptop"
    64: "mouse"
    65: "remote"
    66: "keyboard"
    67: "cell phone"
    68: "microwave"
    69: "oven"
    70: "toaster"
    71: "sink"
    72: "refrigerator"
    73: "book"
    74: "clock"
    75: "vase"
    76: "scissors"
    77: "teddy bear"
    78: "hair drier"
    79: "toothbrush"